### ISSUE TITLE
RuntimeError: Connection reset by peer

### ISSUE THREAD

**Issue by HamidMoghaddam** [catalyst-team/mlcomp#10]
Hi There,

I have a code which works fine with one GPU but when I change my instance to more than one GPU, I get following error:
`Traceback (most recent call last):
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 206, in run_experiment
self._run_stage(stage)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 179, in _run_stage
self._prepare_state(stage)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 74, in _prepare_state
self._get_experiment_components(stage)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 58, in _get_experiment_components
distributed_params=self.experiment.distributed_params
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/catalyst/dl/utils/torch.py", line 50, in process_components
model = DistributedDataParallel(model)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/apex/parallel/distributed.py", line 253, in __init__
flat_dist_call([param.data for param in self.module.parameters()], dist.broadcast, (0,) )
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/apex/parallel/distributed.py", line 75, in flat_dist_call
apply_flat_dist_call(bucket, call, extra_args)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/apex/parallel/distributed.py", line 41, in apply_flat_dist_call
call(coalesced, *extra_args)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 806, in broadcast
work = _default_pg.broadcast([tensor], opts)
RuntimeError: Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/mlcomp/worker/tasks.py", line 251, in build
self.execute()
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/mlcomp/worker/tasks.py", line 202, in execute
dag=self.dag)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/mlcomp/worker/executors/base/executor.py", line 46, in __call__
res = self.work()
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/mlcomp/worker/executors/catalyst/catalyst.py", line 366, in work
runner.run_experiment(experiment, check=args.check)
File "/home/ubuntu/anaconda3/envs/imageprocessing/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 208, in run_experiment
self.state.exception = ex
AttributeError: 'NoneType' object has no attribute 'exception'`

**Comment by lightforever** [comment]
How do you do?!

Could you, please show your MLComp's configuration file? 

Most likely, the error is caused because of default parameters:

MASTER_PORT_RANGE, NCCL_SOCKET_IFNAME: https://github.com/catalyst-team/mlcomp#environment-variables

At the bottom level, NCCL is used for the communication. That needs to know which network interface to use.

You should find your network interface: execute Linux command ```ifconfig```, find your base network interface.

And edit, please, ~/mlcomp/configs/.env file. Then, restart MLComp: 
```
mlcomp-server stop
mlcomp-worker stop

mlcomp-server start
mlcomp-worker start
```
Does it help?

**Comment by HamidMoghaddam** [comment]
Hi there,
I changed the NCCL_SOCKET_IFNAME and it is working now. Thanks for your fast response.
