### ISSUE TITLE
Bash example doesn't work

### ISSUE THREAD

**Issue by maxim1317** [catalyst-team/mlcomp#21]
Bash example failed on single-machine mlcomp version

I've added task with command

```bash
mlcomp dag examples/bash/config.yml
```

Log message:
```
Traceback (most recent call last):
File "/home/username/.local/lib/python3.6/site-packages/mlcomp/worker/tasks.py", line 253, in build
self.download()
File "/home/username/.local/lib/python3.6/site-packages/mlcomp/worker/tasks.py", line 163, in download
raise Exception(f'Executor = {executor_type} not found')
Exception: Executor = bash not found
```

I took examples from 70c3dd3ced5abc50a0c88fd509dd164826b7612d
MLComp version: 19.12

**Comment by lightforever** [comment]
I have just uploaded MLComp v20.1
That version should work. Could you test it?

**Comment by maxim1317** [comment]
Well, I've tried it

I installed it locally from repo and on remote computer from pip

On local computer: 
I can't enter the UI.

Here is the output of
```bash
sudo lsof -i -P -n | grep LISTEN 
```

```
mlcomp-se  9097          username    8u  IPv4 18363169      0t0  TCP *:4201 (LISTEN)
```  

and
```bash
curl -i -X GET http://127.0.0.1:4201 
```
```http
HTTP/1.0 404 NOT FOUND
Content-Type: text/html
Content-Length: 232
Access-Control-Allow-Origin: *
Server: Werkzeug/0.15.4 Python/3.7.3
Date: Tue, 21 Jan 2020 08:45:32 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

Meanwhile, on remote computer I can enter the UI and start the bash example. Although, it has status `not_run` and empty logs 
![image](https://user-images.githubusercontent.com/6140163/72789054-ffc81700-3c43-11ea-9c2a-267f5a26552a.png)

**Comment by maxim1317** [comment]
It works via docker-compose, though

So I guess, I'll provide OS details
```
hostnamectl
```
```
   Static hostname: <hostname>
         Icon name: <iconname>
           Chassis: laptop
        Machine ID: <machine_id>
           Boot ID: <boot_id>
  Operating System: elementary OS 5.1 Hera
            Kernel: Linux 4.15.0-72-generic
      Architecture: x86-64

```

**Comment by lightforever** [comment]
The best method to discover the problem:
- run server via `mlcomp-server start-site --daemon=False`
The server will output logs to the console. You should be able to get http://127.0.0.1:4201 on your laptop. 
- run worker via 'mlcomp-worker start --daemon=False'.  `--daemon=False' will be the default option since next release.

Also, there are logs at ~/mlcomp/logs
Could you show them?
How are you running mlcomp? `mlcomp-server start` ?

**Comment by lightforever** [comment]
`mlcomp-server start-site`

**Comment by maxim1317** [comment]
So, I've cleaned up the logs, restarted `mlcomp migrate` then ran:
```
mlcomp-server start-site
```
and
```
mlcomp-worker start --daemon=False
```

mlcomp-worker successfully spawned 8 workers 


I connected to ui, cleaned up all dags and restarted bash example

And... It didn't work: dag status `not_run`

In server logs I can see that it can't connect to `localhost:6379` (Which is redis server, I guess?)

Should I start server-compose too for this?

Logs are attached:

<details>
<summary>log.txt</summary>

2020-01-21 15:11:54.807 INFO app - start_server: Server TOKEN = 1
2020-01-21 15:12:29.532 INFO __main__ - worker_supervisor: worker_supervisor start
2020-01-21 15:12:29.989 INFO __main__ - worker_supervisor: worker_supervisor run celery
2020-01-21 15:24:18.934 INFO __main__ - _dag: started
2020-01-21 15:24:18.983 INFO __main__ - _dag: config parsed
2020-01-21 15:24:18.996 INFO standard - log_info: create_providers
2020-01-21 15:24:19.011 INFO standard - log_info: load_base
2020-01-21 15:24:19.089 INFO standard - log_info: create_report
2020-01-21 15:24:19.100 INFO standard - log_info: create_dag
2020-01-21 15:24:19.124 INFO standard - log_info: upload
2020-01-21 15:24:19.136 INFO storage - log_info: upload started
2020-01-21 15:24:19.151 INFO storage - log_info: hashes are retrieved
2020-01-21 15:24:19.164 INFO storage - log_info: list of files formed
2020-01-21 15:24:19.179 INFO storage - log_info: inserting DagStorage folders
2020-01-21 15:24:19.190 INFO storage - log_info: inserting Files
2020-01-21 15:24:19.221 INFO storage - log_info: inserting DagStorage Files
2020-01-21 15:24:19.270 INFO standard - log_info: create_tasks
2020-01-21 15:24:19.304 INFO standard - log_info: Done
2020-01-21 15:24:20.000 ERROR supervisor - build: Traceback (most recent call last):
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/app/base.py", line 770, in send_task
    self.backend.on_task_call(P, task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 301, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 135, in consume_from
    return self.start(task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 114, in start
    self._consume_from(initial_task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 142, in _consume_from
    self._pubsub.subscribe(key)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3260, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3148, in execute_command
    self.shard_hint
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/mlcomp/server/back/supervisor.py", line 463, in build
    self.process_tasks()
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/mlcomp/server/back/supervisor.py", line 342, in process_tasks
    self.process_task(task)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/mlcomp/server/back/supervisor.py", line 278, in process_task
    to_send = self._process_task_to_send(executor, task, computers)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/mlcomp/server/back/supervisor.py", line 263, in _process_task_to_send
    self.process_to_celery(task, queue, computer)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/mlcomp/server/back/supervisor.py", line 115, in process_to_celery
    r = execute.apply_async((task.id,), queue=queue, retry=False)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/app/task.py", line 568, in apply_async
    **options
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/app/base.py", line 771, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/oberon/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/kombu/connection.py", line 444, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/app/base.py", line 770, in send_task
    self.backend.on_task_call(P, task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 301, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 135, in consume_from
    return self.start(task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 114, in start
    self._consume_from(initial_task_id)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/celery/backends/redis.py", line 142, in _consume_from
    self._pubsub.subscribe(key)
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3260, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3148, in execute_command
    self.shard_hint
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/home/oberon/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
kombu.exceptions.OperationalError: Error 111 connecting to localhost:6379. Connection refused.

</details>

**Comment by lightforever** [comment]
Yeah, 6379 is the redis's port.

It seems like another program holds 6379 port and redis-server can not start.

I propose the following steps:

1. Change redis port(REDIS_PORT) in ~/mlcomp/configs/.env 

2. If it will not help, try to start it manually: 

https://github.com/catalyst-team/mlcomp/blob/master/mlcomp/bin/redis-server

`./redis-server --port {REDIS_PORT}  --requirepass {REDIS_PASSWORD}` - please change the settings.

redis should start

3. If redis does not start - please show the output

4. The best way: run `server-compose` instead of `mlcomp-server start-site`. This is a production solution.

**Comment by maxim1317** [comment]
I checked `REDIS_PORT` and it was unallocated. 

I've tried to change it to another one, but it I could only star redis manually with `./redis-server --port REDIS_PORT --requirepass REDIS_PASSWORD`

Although, UI return 404 again
![image](https://user-images.githubusercontent.com/6140163/72809075-f357b480-3c6b-11ea-95c4-7c587aa752c0.png)

Yeah, I'll use docker solution, but I'll still be able to test non-docker solution

**Comment by lightforever** [comment]
If you install the library from the repository, you need to build Angular files manually.

1. Clone the repository
2. Build Angular files: https://github.com/catalyst-team/mlcomp/blob/master/mlcomp/server/front/README.md#production
3. pip install .  (i.e. install the library in the root of the repository).

These steps are not needed if the library is install by PyPi server.

Pardon for such a mess. We need to create a clear report functions soon which will check all the details about the installation and functuioning)

**Comment by lightforever** [comment]
If you have other difficulties, please perform `mlcomp report` and create a new issue with the attached report.
