### ISSUE TITLE
No plotly graph in Computers tab

### ISSUE THREAD

**Issue by megachester** [catalyst-team/mlcomp#23]
Why might such a problem appear?
Tasks can be run.
<img width="566" alt="Screenshot 2020-03-04 at 22 11 23" src="https://user-images.githubusercontent.com/18072972/75914385-b6cfc900-5e65-11ea-8461-76165a2b79b3.png">

**Comment by lightforever** [comment]
@megachester , Looks like an internal error.

The program has last activity = null for that computer.

Could you please provide me with the log file?

`cat ~/mlcomp/logs/log.txt`

**Comment by megachester** [comment]
```
2020-03-04 19:22:33.449 ERROR app - decorated: Requested Url: /api/computer_sync_end

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mlcomp/server/back/app.py", line 102, in decorated
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mlcomp/server/back/app.py", line 164, in computer_sync_end
    meta = yaml_load(computer.meta)
  File "/usr/local/lib/python3.6/dist-packages/mlcomp/utils/io.py", line 22, in yaml_load
    res = yaml.load(stream, Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by lightforever** [comment]
@megachester , how have you installed the library? Via Pypi or from the Github sources?

Please try version 20.2.4.

For example: 

```
# stop server and workers
pip install -U mlcomp
mlcomp migrate
# start server and workers
```

Does it help?

**Comment by megachester** [comment]
No, it didn't help

**Comment by lightforever** [comment]
There is the version `20.2.4b`. 

Please update mlcomp to it.

Then:

1. `mlcomp report`
This command will create a report. Please attach it to the issue. (I hope your logs do not contain secure information).

2. Please open the Console in your browser. Are there errors?

**Comment by megachester** [comment]
What do you mean by Console?

**Comment by lightforever** [comment]
1. Yeah, it would be better

2. https://kb.mailster.co/how-can-i-open-the-browsers-console/

https://web.dev/errors-in-console/

**Comment by megachester** [comment]
2. You were right, there are errors of such type:
`Error: InvalidPipeArgument: 'Unable to convert "2020-03-12 12:45:17Z" into a date' for pipe 'DatePipe'`

**Comment by megachester** [comment]
1. [report1203.zip](https://github.com/catalyst-team/mlcomp/files/4324834/report1203.zip)

**Comment by lightforever** [comment]
Sorry, but I have no idea why it happens.

You could debug the issue:

1. Open tables computers and docker in your database and check them on `null` values

2. Try to open the page in a different browser. For example, I use Google Chrome.

**Comment by megachester** [comment]
Thanks! Opening front in Chrome helped. The problem is with Safari.
