### ISSUE TITLE
Error when trying to create model

### ISSUE THREAD

**Issue by megachester** [catalyst-team/mlcomp#25]
This message appears in a pop-up window after pressing OK button to create model
```
Error:

    Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mlcomp/server/back/app.py", line 103, in decorated
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mlcomp/server/back/app.py", line 325, in model_add
    dag_model_add(_write_session, data)
  File "/usr/local/lib/python3.6/dist-packages/mlcomp/server/back/create_dags/model_add.py", line 47, in dag_model_add
    'fold': data['fold']
KeyError: 'fold'
```

**Comment by lightforever** [comment]
Please try https://github.com/catalyst-team/mlcomp/issues/23#issuecomment-595333548
Does it help?

**Comment by megachester** [comment]
The error above is gone, but there is a new one in task, here's the message:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/mlcomp/worker/tasks.py", line 279, in build
self.execute()
File "/usr/local/lib/python3.6/dist-packages/mlcomp/worker/tasks.py", line 230, in execute
dag=self.dag)
File "/usr/local/lib/python3.6/dist-packages/mlcomp/worker/executors/base/executor.py", line 125, in __call__
res = self.work()
File "/usr/local/lib/python3.6/dist-packages/mlcomp/worker/executors/model.py", line 240, in work
traced = trace_model_from_checkpoint(src_log, self, file=self.file)
File "/usr/local/lib/python3.6/dist-packages/mlcomp/worker/executors/model.py", line 140, in trace_model_from_checkpoint
config = safitty.load(config_path)
File "/usr/local/lib/python3.6/dist-packages/safitty/parser.py", line 113, in load
raise Exception(f"Path '{path}' doesn't exist!")
Exception: Path '/root/mlcomp/tasks/48/log/configs/_config.json' doesn't exist!
```

I guess it should be `logs` instead of `log` in config path `/root/mlcomp/tasks/48/log/configs/_config.json`

**Comment by megachester** [comment]
#26

**Comment by lightforever** [comment]
The problem is solved. The issue is closed.
