### ISSUE TITLE
sqlite InterfaceError

### ISSUE THREAD

**Issue by Trigram19** [catalyst-team/mlcomp#31]
Trying to run mlcomp dag and getting this errorL
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/mlcomp", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/__main__.py", line 87, in dag
    _dag(config, control_reqs=control_reqs, params=params)
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/__main__.py", line 50, in _dag
    control_reqs=control_reqs
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/server/back/create_dags/standard.py", line 273, in dag_standard
    return builder.build()
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/server/back/create_dags/standard.py", line 244, in build
    self.upload()
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/server/back/create_dags/standard.py", line 116, in upload
    control_reqs=self.control_reqs)
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/worker/storage.py", line 120, in upload
    self.file_provider.add(file)
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/db/providers/base.py", line 50, in add
    self._session.add(obj, commit=commit)
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/db/core/db.py", line 99, in add
    raise e
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/db/core/db.py", line 96, in add
    self.commit()
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/db/core/db.py", line 107, in commit
    raise e
  File "/opt/conda/lib/python3.7/site-packages/mlcomp/db/core/db.py", line 104, in commit
    super().commit()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 2 - probably unsupported type.
[SQL: INSERT INTO file (md5, created, content, project, dag, size) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('2a56845cd8f723587ab2b10cf84107c4', '2020-10-05 05:55:37.139080', <memory at 0x7f8fafdd4940>, 1, 1, 1337753633)]
(Background on this error at: http://sqlalche.me/e/rvf5)
```

Most probably could be an error in my configuration, but not 100 percent sure.

**Comment by Trigram19** [comment]
So sorry - turns out it was indeed an error in my configuration files.
